spring.application.name=JobDock

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/jobdock_db
spring.datasource.username=postgres
spring.datasource.password=KGade@45

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=a2dhZGUtam9iZG9jay1zZWNyZXQta2V5LTIwMjYtc3VwZXItc2VjcmV0
jwt.expiration=86400000
